# Generated by Django 4.2 on 2023-05-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chat_id',
            field=models.CharField(db_index=True, max_length=255),
            preserve_default=False,
        ),
    ]
